language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script: pytest
deploy:
  provider: heroku
  api_key:
    secure: F/qE7T1yd5PkKxTFObHJUUhpixF4z9cQVdEBwiHEpfH/xPLe4RYH49c65Bo9qRVp80g9xoOXonFnZR+cs2VyT5/GXXkbpbPRIbDz4xMq1YlZWQ8GttdJAfuCPseyLZLQhkC6XevEaA+Li+dyqcTuN39b/LOBRt1NprKejRw2f5xwWw94Rq635e8y79uffiCIMNL9+8ibWX6xdaqSSWA8OM/y/tWmS9yGdX42L4N525+5fFcvy34lWAoDwlMJkn+sbwh8gelBFAaAfnzNEL6ckJDFYFPHs9EJj9bjJ43jAFlV2wFmkFd/FVVoG8/eeOx6YOD9Hh/lYXL7qHJChMS1iidy0wLiNv/UT/MCTcT3qBkHfIXetcJexvoZyOqNpF0EvUBXHBMR+d+M2EydMYKuJv2QU13cfBmycMvC0kYB3qMvK1XQTIkE8EqmDfgU2LYlmnpGHG7YCfp8zSiebPAa67l38q5I8C/mBLvpcAvPQbz1L0J+JshViVCSav+eZAJAFcuh7xEW1s2A69DU3TGuaQXAcOR7up71tB50ASjp7mcehzgrwkn+CCkH18pghmOWTjqKu3dadgbn8T9z6zsu8SkEyBEuRGQUKQpXgK/8dxY9YUB4+oOAi+hmG7BOaFV6503btS7QUj4B9mtai/34Jp3TOZ3rNj8kfYQNmFO6uFk=
