language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script: pytest
deploy:
  provider: heroku
  api_key:
    secure: cea8MUZesujnqsvMiM2C6s/4Rqk6jLQ7l20h1QaS26OS09HyLu+ceZ8dHkQqL2FZJDFYxvsBA+czzqpXwV/CS+WAsnWDH/1h61nwajadW5nmAf8gBKf/s9z6JDz50dD0mXfNahJ39SM1QBFGL86Q0KuVJuWAvFeFV9oMnPyXH10jhCLSAthTLDfg3PM72zGD1iETRgfU6yMevDxNvPUpYEPGUMU4cFLlowbVRNproKIGRK7XbvWd/ZmS7POwgGC3dnkYp1evoAvcJnpBxNzvHcVArNpaMzZsCh8usKKJUgQ/Q8ppTbHD1LYOkrTRVvdTIcg8BZBLmGYeSl+QUc7DO0q0qfJ5M/Et0T2kkHE0n2iglhs51Q17wTcM7gXj8sJdy73ERst5HqKHzppm7DHOg6Eq4yNGverfHRZnaDPJpK7KoR3znJaityqF5n7ZM1L7erXrDa8zim8J6bhfhsc9sho3EqPo2oZqxGd4Oxd+eJ2Dp5oqv2y9bLtT8mmYdO26FU++sZm8V43dIJrvXFvyY6gsT6Y6fypN2U83vOussgKX4G04f4WS1TJk48tKOnVVgIka9g8/+sUpofZAoDKDthMhxiCaOEDIcKyjaCq2DotHhOwT4jIRq9o2rh+dCPpA4Rif9kd7didBdukToj/2dcY1TkFnUMZki7welFvIink=
